'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { DataContext } from "@/contexts/context";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [input,setinput] = useState({
    firstCharacter: "",
    secondCharacter: "",
    moral: ""
  })
  const [transcript, setTranscript] = useState('');
  return (
    <html lang="en">
      <body className={inter.className}>
      <DataContext.Provider value={{input,setinput,transcript, setTranscript}}>
        <Navbar />

        {children}

        <Footer/>
        </DataContext.Provider>
      </body>
    </html>
  );
}
